owner: matthew-hajec
repo: upptime_chess_quo

sites:
  - name: ChessQuo
    url: https://chessquo.com

status-website:
  baseUrl: /upptime_chess_quo
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ChessQuo Uptime
  introTitle: "**ChessQuo Status** — monitoring site uptime via GitHub Actions"
  introMessage: |
    This is the automated status page for [ChessQuo](https://chessquo.com),
    built using [Upptime](https://github.com/upptime/upptime). All checks are
    powered by GitHub Actions, no server required.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/matthew-hajec/uptime_chess_quo
