owner: matthew-hajec  # Replace with your GitHub username
repo: chessquo-status # This will be the name of your Upptime repo

sites:
  - name: ChessQuo
    url: https://chessquo.com

status-website:
  cname: status.chessquo.com  # Optional custom domain, change/remove if not needed
  # baseUrl: /chessquo-status  # Uncomment if not using custom domain
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ChessQuo Uptime
  introTitle: "**ChessQuo Status** — monitoring site uptime via GitHub Actions"
  introMessage: |
    This is the automated status page for [ChessQuo](https://chessquo.com),
    built using [Upptime](https://github.com/upptime/upptime). All checks are
    powered by GitHub Actions, no server required.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/matthew-hajec/chessquo-status
