owner: matthew-hajec
repo: portfolio_upptime

sites:
  - name: ChessQuo
    url: https://chessquo.com/
  - name: Cryptalyx
    url: https://cryptalyx.com/

status-website:
  baseUrl: /portfolio_upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Portfolio Uptime
  introTitle: "Portfolio monitoring site"
  introMessage: |
    This is the automated status page for [my](https://github.com/matthew-hajec) portfolio projects,
    built using [Upptime](https://github.com/upptime/upptime). All checks are
    powered by GitHub Actions, no server required.
  navbar:
    - title: Status
      href: https://matthew-hajec.github.io/portfolio_upptime/
    - title: GitHub
      href: https://github.com/matthew-hajec/uptime_chess_quo
